1. Write a Python program using lambda to calculate the square of a number
entered by the user.

In [3]:
sq=lambda x: x ** 2
#we take a no as input and then use sq. Here, sq uses lambda function
num=float(input('enter a number:'))
res = sq(num)
print(res)

enter a number:6
36.0


2. Use map to double all the elements in the list: [1, 2, 3, 4, 5].


In [5]:
lst=[1, 2, 3, 4, 5]
doub = list(map(lambda x: x * 2, lst))
#we use list, map, lambda functions to work on our list lst. It returns the double of all elements
print(doub)

[2, 4, 6, 8, 10]


3. Use filter to extract all even numbers from the list: [10, 15, 20, 25, 30]

In [6]:
lst=[10,15,20,25,30]
even_lst=list(filter(lambda x: x % 2 == 0, lst))
#we use lambda function for filtering out even nos. we know that for a number to be even, number%2==0
print(even_lst)

[10, 20, 30]


4. Write a one-liner lambda function to check if a given number is a palindrome.

In [7]:
res=lambda x:str(x)==str(x)[::-1]
num=int(input('enter a number:'))
# here, we start from the end and slice with a step size of 1... in the end, we compare the original and reversed values to check palindrome
print(res(num))

enter a number:88
True


7. Create a class Person with attributes name and age. Add a method greet that
prints a greeting with the name. Create an object of the class and call the greet
method

In [8]:
class Person:
  #we create a class Person with the attributes name and age. Then we define a method greet on it
    def __init__(self,name,age):
        self.name=name
        self.age=age
    def greet(self):
        print(f'hello {self.name}')

10.Write a program to print the first 10 natural numbers using a for loop.

In [9]:
for i in range(1,11):
    print(i)
    # the for loop prints all numbers from 1 to (11-1 ie 10)

1
2
3
4
5
6
7
8
9
10


12.Write a Python program to print the multiplication table of a given number using
a while loop.


In [10]:
for i in range(1,11):
  # here we use the for loop to print a table of 5
    print(f'5*{i}={5*i}')

5*1=5
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
5*10=50


15.Write a Python program to determine the grade of a student based on their
marks:
• Marks >= 90: Grade A
• Marks >= 75: Grade B
• Marks >= 50: Grade C
• Otherwise: Grade F

In [11]:
Marks=int(input('enter your marks:'))
# we use if and elif to print grades  for various categories of marks
if Marks >= 90:
    print('Grade A')
elif Marks >= 75:
    print('Grade B')
elif Marks >= 50:
    print('Grade C')

enter your marks:87
Grade B


17.Write a function to find the maximum of three numbers entered by the user.

In [12]:
def maxi(a,b,c):
  # we use if and elif to individually compare and return maximum of 3 numbers
    if a>b and a>c:
        return a
    elif b>a and b>c:
        return b
    else:
        return c

19.Write a Python program to reverse a string using a for loop

In [18]:
stri=input('enter a string:')
rev=''
for i in stri:
  #we take a string as input and then keep concatenating to rev string which returns the reversed string
    rev=i+rev
print(rev)

enter a string:souparna
anrapuos


NumPy Questions

1. Create a NumPy array of zeros with shape (3, 4).

In [19]:
import numpy as np
# we create an array of zeros under numpy by specifying size as parameter
z = np.zeros((3, 4))
print("")
print(z)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Write a NumPy program to compute the square root of each element in the array
[1, 4, 9, 16].


In [20]:
import numpy as np
# we use sqrt function to find square root of each number
arr=np.array([1,4,9,16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


7. Compute the sum of all elements in the array np.array([2, 3, 4, 5, 6])

In [21]:
import numpy as np
arr=np.array([2,3,4,5,6])
# we use np.sum() function to find the reqd summ
print(np.sum(arr))

20


8. Find the minimum value in the array np.array([1, 5, 9, 3, 6]) using np.min().


In [22]:
import numpy as np
# here we use np.min() to find the minimum
arr=np.array([1,5,9,3,6])
print(np.min(arr))

1


9. Find the maximum value in the array np.array([1, 5, 9, 3, 6]) using np.max()

In [23]:
import numpy as np
# here we use np.max() to find the maximum
arr=np.array([1,5,9,3,6])
print(np.max(arr))

9


10.Use np.ceil() to round the elements of the array np.array([1.2, 2.5, 3.7, 4.9]) to
the nearest greater integer.


In [25]:
import numpy as np
# here we use np.ceil() to find the upper limit/ceil
arr=np.array([1.2,2.5,3.7,4.9])
print(np.ceil(arr))

[2. 3. 4. 5.]
[2. 3. 4. 5.]


Generate an array of 5 random integers between 10 and 50 using
np.random.randint().


In [26]:
import numpy as np
# here 10, 50 define the range, while 5 is for the number of elements reqd
arr=np.random.randint(10,50,5)
print(arr)

[11 28 45 46 19]


Generate a 3x3 matrix of random numbers from a normal distribution with mean
0 and standard deviation 1 using np.random.randn().


In [27]:
import numpy as np
# we create a 3*3 matrix whose mean=0 and std deviation is 1
arr=np.random.randn(3,3)
print(arr)

[[ 0.05360869 -0.8859736   0.93915937]
 [ 0.45060728  1.90491695  0.86444578]
 [-0.91065062 -0.390145    0.72984788]]


19.Reshape a 1D array [1, 2, 3, 4, 5, 6] into a 2x3 matrix using np.reshape()

In [28]:
import numpy as np
# we have an array that we reshape to (2,3)
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))


[[1 2 3]
 [4 5 6]]


20.Slice the first two elements from the array np.array([10, 20, 30, 40, 50]).

In [30]:
import numpy as np
arr=np.array([10,20,30,40,50])
# we use [:index] to slice upto that index(exclusive)
print(arr[:2])


[10 20]
